# First we will convert the .xlsx file into .csv

In [2]:
import pandas as pd 
read_file = pd.read_excel ("Coffee_Shop_Sales_Dataset_012124.xlsx") 

read_file.to_csv("Coffee_Shop_Sales_Dataset.csv", index = None, header=True)

df = pd.DataFrame(pd.read_csv("Coffee_Shop_Sales_Dataset.csv")) 

# show the dataframe 
df

,Transaction ID,Transaction Date,Transaction Time,Transaction Quantity,Store ID,Store Location,Product ID,Unit Price,Product Category,Product Type,Product Detail
0,1,2023-01-01,07:06:11,2,5.0,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5.0,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5.0,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5.0,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5.0,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
149982,149436,2023-06-30,19:44:46,1,3.0,Astoria,60,3.75,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Rg
149983,149437,2023-06-30,19:44:46,2,3.0,Astoria,72,3.25,Bakery,Scone,Ginger Scone
149984,149438,2023-06-30,19:45:16,1,3.0,Astoria,41,4.25,Coffee,Barista Espresso,Cappuccino Lg
149985,149439,2023-06-30,19:45:52,1,3.0,Astoria,46,2.50,Tea,Brewed Green tea,Serenity Green Tea Rg
149986,149440,2023-06-30,19:46:02,2,8.0,Hell's Kitchen,55,4.00,Tea,Brewed Chai tea,Morning Sunrise Chai Lg

# Cleaning null values

In [3]:
df.dropna(subset=["Store Location", "Store ID"], inplace=True)
df.to_csv("Coffee_Shop_Sales_Dataset.csv", index=False)

# Removing the seconds from the time in "Transaction Time" column

In [4]:
df['Transaction Time'] = pd.to_datetime(df['Transaction Time'], format='%H:%M:%S')
df['Transaction Time'] = df['Transaction Time'].dt.strftime('%H:%M')
df.to_csv("Coffee_Shop_Sales_Dataset.csv", index=False)

# Removing duplicates

In [5]:
df = df.drop_duplicates(subset="Transaction ID", keep=False)
df.tail(20)

,Transaction ID,Transaction Date,Transaction Time,Transaction Quantity,Store ID,Store Location,Product ID,Unit Price,Product Category,Product Type,Product Detail
148225,148566,2023-06-30,08:17,2,8.0,Hell's Kitchen,63,0.80,Flavours,Regular syrup,Carmel syrup
148226,148567,2023-06-30,08:17,1,8.0,Hell's Kitchen,38,3.75,Coffee,Barista Espresso,Latte
148227,148568,2023-06-30,08:17,2,8.0,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup
148228,148569,2023-06-30,08:17,1,3.0,Astoria,30,3.00,Coffee,Gourmet brewed coffee,Columbian Medium Roast Lg
149100,149441,2023-06-30,19:46,1,8.0,Hell's Kitchen,27,3.50,Coffee,Organic brewed coffee,Brazilian Lg
149101,149442,2023-06-30,19:46,1,8.0,Hell's Kitchen,75,3.50,Bakery,Pastry+,Croissant
149102,149443,2023-06-30,19:46,2,3.0,Astoria,50,2.50,Tea,Brewed Black tea,Earl Grey Rg
149103,149444,2023-06-30,19:51,2,3.0,Astoria,26,3.00,Coffee,Organic brewed coffee,Brazilian Rg
149104,149445,2023-06-30,19:52,2,3.0,Astoria,34,2.45,Coffee,Premium brewed coffee,Jamaican Coffee River Sm
149105,149446,2023-06-30,19:53,1,3.0,Astoria,24,3.00,Coffee,Drip coffee,Our Old Time Diner Blend Lg
149106,149447,2023-06-30,19:56,1,8.0,Hell's Kitchen,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
149107,149448,2023-06-30,19:57,2,3.0,Astoria,54,2.50,Tea,Brewed Chai tea,Morning Sunrise Chai Rg
149108,149449,2023-06-30,19:57,1,3.0,Astoria,70,3.25,Bakery,Scone,Cranberry Scone
149109,149450,2023-06-30,20:08,2,8.0,Hell's Kitchen,55,4.00,Tea,Brewed Chai tea,Morning Sunrise Chai Lg
149110,149451,2023-06-30,20:16,2,5.0,Lower Manhattan,42,2.50,Tea,Brewed herbal tea,Lemon Grass Rg
149111,149452,2023-06-30,20:18,2,8.0,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25,2,8.0,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31,1,8.0,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57,1,8.0,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57,2,8.0,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [6]:
df.to_csv("Coffee_Shop_Sales_Dataset.csv", index=False)

# Rearranging the dataset

In [7]:
desired_columns_order = ["Transaction ID", "Transaction Date","Transaction Time", "Store ID","Store Location", "Product ID", "Unit Price", "Transaction Quantity", "Product Category", "Product Type", "Product Detail"]
df = df[desired_columns_order]
df.head(20)

,Transaction ID,Transaction Date,Transaction Time,Store ID,Store Location,Product ID,Unit Price,Transaction Quantity,Product Category,Product Type,Product Detail
0,1,2023-01-01,07:06,5.0,Lower Manhattan,32,3.00,2,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08,5.0,Lower Manhattan,57,3.10,2,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14,5.0,Lower Manhattan,59,4.50,2,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20,5.0,Lower Manhattan,22,2.00,1,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22,5.0,Lower Manhattan,57,3.10,2,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
5,6,2023-01-01,07:22,5.0,Lower Manhattan,77,3.00,1,Bakery,Scone,Oatmeal Scone
6,7,2023-01-01,07:25,5.0,Lower Manhattan,22,2.00,1,Coffee,Drip coffee,Our Old Time Diner Blend Sm
7,8,2023-01-01,07:33,5.0,Lower Manhattan,28,2.00,2,Coffee,Gourmet brewed coffee,Columbian Medium Roast Sm
8,9,2023-01-01,07:39,5.0,Lower Manhattan,39,4.25,1,Coffee,Barista Espresso,Latte Rg
9,10,2023-01-01,07:39,5.0,Lower Manhattan,58,3.50,2,Drinking Chocolate,Hot chocolate,Dark chocolate Rg
10,11,2023-01-01,07:43,5.0,Lower Manhattan,56,2.55,1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Rg
11,12,2023-01-01,07:44,5.0,Lower Manhattan,33,3.50,2,Coffee,Gourmet brewed coffee,Ethiopia Lg
12,13,2023-01-01,07:45,5.0,Lower Manhattan,51,3.00,1,Tea,Brewed Black tea,Earl Grey Lg
13,14,2023-01-01,07:48,5.0,Lower Manhattan,57,3.10,1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
14,15,2023-01-01,07:52,5.0,Lower Manhattan,87,3.00,2,Coffee,Barista Espresso,Ouro Brasileiro shot
15,16,2023-01-01,07:59,5.0,Lower Manhattan,47,3.00,2,Tea,Brewed Green tea,Serenity Green Tea Lg
16,17,2023-01-01,07:59,5.0,Lower Manhattan,79,3.75,1,Bakery,Scone,Jumbo Savory Scone
17,18,2023-01-01,08:00,8.0,Hell's Kitchen,42,2.50,1,Tea,Brewed herbal tea,Lemon Grass Rg
18,19,2023-01-01,08:00,8.0,Hell's Kitchen,59,4.50,2,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
19,20,2023-01-01,08:11,8.0,Hell's Kitchen,61,4.75,1,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Lg

In [9]:
df.to_csv("Coffee_Shop_Sales_Dataset.csv", index=False)